"""THIS IS THE MAIN PROJECT BODY STRUCTURE.
 THE MAIN MODULE WILL COMBINE AND ASSEMBLE ALL THE REST OF THE CODE PIECES.
 IT IS RESPONSIBLE FOR THE WORKFLOW WHILE OTHER MODULES MUST BE IMPORTED TO RUN THIS PROJECT.
 IT CONTAINS ONLY ONE FUNCTION—RUN. AS A START THE WELCOME FUNCTION IS CALLED, WHICH IS USED AS A HEADER.
 JUST BELOW THE WELCOME MESSAGE, THE PRINT_DATA FUNCTION IS BASED
 AND THE MAIN PART IS LOADED WITH A MAIN_MENU FUNCTION."""

import tui
import process


def main():
    tui.welcome_text(title="Disneyland Review Analyser")
    tui.print_data(amount=len(process.data))
    tui.main_menu()


if __name__ == "__main__":
    main()
